### ISSUE TITLE
ImportError: No module named _hip when  i run the command python ExoPlotter.py

### ISSUE THREAD

**Issue by huangshizhe** [ArayCHN/ExoskeletonForKids#2]
Traceback (most recent call last):
  File "ExoPlotter.py", line 137, in <module>
    main()
  File "ExoPlotter.py", line 101, in main
    import trajectory_generator as traj
  File "/home/huangshizhe/ExoskeletonForKids-master/py/trajectory_generator.py", line 1, in <module>
    import build.hip as hip
  File "/home/huangshizhe/ExoskeletonForKids-master/py/build/hip.py", line 28, in <module>
    _hip = swig_import_helper()
  File "/home/huangshizhe/ExoskeletonForKids-master/py/build/hip.py", line 20, in swig_import_helper
    import _hip
ImportError: No module named _hip

**Comment by kpaonaut** [comment]
Please recompile the entire package per the guidance in README and run the builds from your own computer. The project is very old and the binary files built from my laptop may not be executable on your system any more.

**Comment by antonyalexos** [comment]
can you give the directions for that? I still have issues running it.
